### PR TITLE
Fix cdd headers

### PR DESCRIPTION
**Pull request by kliem**
This is supposed to fix issue #15

### CODE REVIEW

**Comment by kliem** [comment]
My approach seems to work fine. I succesfully updated cdd in my local sage and installed latte-int on top of it.
However, maybe it is better to introduce a macro `CDDFOLDER` or similar which takes the value `cddlib/` or `cdd/` or the empty string.

cdd moved the headers because of conflicts. If we now just include the folder `cddlib` for compiling, we might have those conflicts again.

**Comment by mkoeppe** [comment]
I think I would prefer the solution with a macro - which matches how I deal with lidia in `code/lidia-include.hin`

**Comment by mkoeppe** [comment]
Also it's probably best to try to find cddlib using pkgconfig (as in #17) and only fall back to the direct checks if pkgconfig fails

**Comment by kliem** [comment]
Something went wrong with the checks, but I'm pretty happy with it now.

One has to be careful that the system cdd does not leak in, when setting the path.

With this branch sage finds successfully the headers in cddlib of sage (and not the ones in cdd by my system). However, when I change `-with-cddlib=$SAGE_LOCAL` to `-with-cddlib=yes` the system cdd leaks in, which is supposed to happen I guess.

**Comment by mkoeppe** [comment]
I have taken some bits of this for what is now on `master` in 3899554c1eb1c463496c828986946c49d9912dbb and 850effd7e64cc577a5aebb8278e5d73ab28d760a

**Pull request merged**
